#!/usr/bin/env python3
"""Synthesize positive ("hey eliza") and negative wake-word training clips
using the locally-built llama-omnivoice-server.

This is the synthetic-data path for the wake-word head trainer. Positives are
generated by speaking "hey eliza" with prosody / voice variations; negatives
are generated by speaking short distractor phrases that should never trigger
the wake word. All clips are written as 16 kHz mono PCM16 WAVs (the format
the trainer's `read_wav_pcm16_mono` expects), trimmed to a fixed window.

The output directory layout:
  <out>/positives/         many "hey eliza" wavs (training)
  <out>/heldout-positives/ ~20 "hey eliza" wavs (eval, distinct seeds)
  <out>/negatives/         distractor wavs (training)
  <out>/heldout-negatives/ ~20 distractor wavs (eval, distinct seeds)
  <out>/manifest.json      provenance: phrase, voice/seed grid, sample count

Provenance is captured in manifest.json so reviewers can audit the chain.
"""

from __future__ import annotations

import argparse
import json
import os
import random
import shutil
import struct
import subprocess
import sys
import wave
from datetime import datetime, timezone
from pathlib import Path

OMNIVOICE_BIN = Path(
    "/home/shaw/.eliza/local-inference/bin/dflash/linux-x64-cuda-fused/llama-omnivoice-server"
)
OMNIVOICE_LIBS = Path(
    "/home/shaw/.eliza/local-inference/bin/dflash/linux-x64-cuda-fused"
)
TTS_MODEL = Path(
    "/home/shaw/.eliza/local-inference/models/eliza-1-1_7b.bundle/tts/omnivoice-base-Q4_K_M.gguf"
)
TTS_CODEC = Path(
    "/home/shaw/.eliza/local-inference/models/eliza-1-1_7b.bundle/tts/omnivoice-tokenizer-Q4_K_M.gguf"
)
TARGET_SAMPLE_RATE = 16_000

# Prosody / voice instructions — drawn from OmniVoice's "Valid English items"
# enum (the model rejects anything not in this list, hard-fails on the first
# invalid item). Combinations are comma+space joined; we exercise the
# gender × age × pitch × accent grid.
INSTRUCTS = [
    "female, young adult, moderate pitch",
    "female, young adult, high pitch",
    "female, middle-aged, low pitch",
    "female, young adult, american accent",
    "female, young adult, british accent",
    "female, young adult, whisper",
    "female, teenager, moderate pitch",
    "female, elderly, low pitch",
    "female, young adult, high pitch, australian accent",
    "female, young adult, indian accent",
    "male, young adult, moderate pitch",
    "male, young adult, low pitch",
    "male, young adult, very low pitch",
    "male, middle-aged, moderate pitch",
    "male, young adult, american accent",
    "male, young adult, british accent",
    "male, young adult, canadian accent",
    "male, teenager, moderate pitch",
    "male, elderly, low pitch",
    "male, young adult, high pitch",
    "male, young adult, japanese accent",
    "male, young adult, russian accent",
    "female, young adult, chinese accent",
    "female, young adult, korean accent",
    "child, high pitch",
    "child, moderate pitch",
]

# Distractor phrases — varied content so the head learns "not the wake phrase",
# not just "not this exact distractor". Mix wake-phrase-shaped negatives
# (rhymes/near-misses) with totally unrelated speech.
DISTRACTOR_PHRASES = [
    # Near-misses (the head needs to reject these)
    "hey alexa",
    "hey jarvis",
    "hey siri",
    "hey google",
    "hey computer",
    "hello eliza",
    "hi eliza",
    "play eliza",
    "hey lisa",
    "hey alyssa",
    "okay eliza",
    "stop eliza",
    "they realize",
    "they leave",
    "hey there",
    "hey buddy",
    # Common everyday phrases (general speech)
    "what time is it",
    "set a timer for five minutes",
    "play some music",
    "send a message to mom",
    "turn off the lights",
    "what is the weather today",
    "how is the traffic",
    "open the front door",
    "tell me a joke",
    "remind me to buy milk",
    "what is on my schedule",
    "call my brother",
    "check the temperature outside",
    "show me the news",
    "good morning everyone",
    "thank you very much",
    "see you later",
    "have a nice day",
    "i need a coffee",
    "the meeting starts at three",
    "let me think about it",
    "that sounds great",
    "i agree with you",
    "could you repeat that",
    "i did not catch that",
    "where did you put my keys",
    "the project deadline is friday",
    "i will be there in ten minutes",
    "save the file please",
    "open a new browser tab",
]


def have_ffmpeg() -> bool:
    return shutil.which("ffmpeg") is not None


def synth_one(text: str, instruct: str, seed: int, out_wav: Path, *, lang: str = "English") -> bool:
    """Run llama-omnivoice-server once. Returns True on success."""
    out_wav.parent.mkdir(parents=True, exist_ok=True)
    env = os.environ.copy()
    env["LD_LIBRARY_PATH"] = (
        f"{OMNIVOICE_LIBS}:" + env.get("LD_LIBRARY_PATH", "")
    )
    cmd = [
        str(OMNIVOICE_BIN),
        "--model", str(TTS_MODEL),
        "--codec", str(TTS_CODEC),
        "--lang", lang,
        "--instruct", instruct,
        "--seed", str(seed),
        "-o", str(out_wav),
    ]
    try:
        proc = subprocess.run(
            cmd,
            input=text.encode("utf-8"),
            env=env,
            capture_output=True,
            timeout=90,
        )
    except subprocess.TimeoutExpired:
        return False
    if proc.returncode != 0:
        sys.stderr.write(
            f"[synth] failed text={text!r} seed={seed} rc={proc.returncode}\n"
            f"  stderr tail: {proc.stderr.decode('utf-8', errors='replace')[-400:]}\n"
        )
        return False
    return out_wav.is_file() and out_wav.stat().st_size > 1000


def downsample_to_16k_mono(src: Path, dst: Path) -> bool:
    """OmniVoice produces 24 kHz mono WAV; the trainer needs 16 kHz mono PCM16.
    Use ffmpeg to resample. Returns True on success."""
    proc = subprocess.run(
        [
            "ffmpeg", "-y", "-loglevel", "error",
            "-i", str(src),
            "-ar", str(TARGET_SAMPLE_RATE),
            "-ac", "1",
            "-sample_fmt", "s16",
            str(dst),
        ],
        capture_output=True,
    )
    if proc.returncode != 0:
        sys.stderr.write(
            f"[ffmpeg] failed src={src} rc={proc.returncode}\n"
            f"  stderr: {proc.stderr.decode('utf-8', errors='replace')[-400:]}\n"
        )
        return False
    return dst.is_file()


def pad_or_trim(wav_path: Path, target_seconds: float = 2.0) -> None:
    """Pad with silence (or trim) so every clip is the same duration.

    openWakeWord trainer slides a 16-embedding window. A clip < ~1.4s yields
    zero windows. We pad to 2.0s so the head sees at least a few windows per
    clip, with the phrase centered.
    """
    target_samples = int(target_seconds * TARGET_SAMPLE_RATE)
    with wave.open(str(wav_path), "rb") as w:
        if w.getframerate() != TARGET_SAMPLE_RATE or w.getnchannels() != 1 or w.getsampwidth() != 2:
            raise RuntimeError(
                f"{wav_path}: not 16 kHz mono PCM16 — was "
                f"{w.getframerate()}Hz/{w.getnchannels()}ch/{w.getsampwidth()*8}bit"
            )
        frames = w.readframes(w.getnframes())
        n = w.getnframes()
    if n >= target_samples:
        # Center-trim: keep the middle target_samples.
        start = (n - target_samples) // 2
        frames = frames[start * 2 : (start + target_samples) * 2]
    else:
        # Center-pad with silence: half before, half after.
        pad = target_samples - n
        pre = pad // 2
        post = pad - pre
        frames = b"\x00\x00" * pre + frames + b"\x00\x00" * post
    with wave.open(str(wav_path), "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(TARGET_SAMPLE_RATE)
        w.writeframes(frames)


def synth_clip(
    text: str,
    instruct: str,
    seed: int,
    final_path: Path,
    *,
    tmp_dir: Path,
    target_seconds: float = 2.0,
) -> bool:
    raw_wav = tmp_dir / f"raw-{seed:06d}.wav"
    if not synth_one(text, instruct, seed, raw_wav):
        return False
    if not downsample_to_16k_mono(raw_wav, final_path):
        raw_wav.unlink(missing_ok=True)
        return False
    raw_wav.unlink(missing_ok=True)
    try:
        pad_or_trim(final_path, target_seconds=target_seconds)
    except Exception as exc:
        sys.stderr.write(f"[pad] failed {final_path}: {exc}\n")
        final_path.unlink(missing_ok=True)
        return False
    return True


def synthesize_set(
    out_dir: Path,
    *,
    phrases: list[str],
    instructs: list[str],
    count: int,
    seed_base: int,
    label: str,
    tmp_dir: Path,
) -> int:
    out_dir.mkdir(parents=True, exist_ok=True)
    written = 0
    target = count
    seed_iter = seed_base
    attempts = 0
    max_attempts = target * 3
    while written < target and attempts < max_attempts:
        attempts += 1
        text = phrases[attempts % len(phrases)]
        instruct = instructs[attempts % len(instructs)]
        out = out_dir / f"{label}-{written:05d}.wav"
        if synth_clip(text, instruct, seed_iter, out, tmp_dir=tmp_dir):
            written += 1
            if written % 10 == 0 or written == 1:
                print(f"[synth:{label}] wrote {written}/{target}")
        seed_iter += 1
    if written < target:
        sys.stderr.write(
            f"[synth:{label}] WARN: only wrote {written}/{target} after {attempts} attempts\n"
        )
    return written


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out-dir", type=Path, required=True)
    ap.add_argument("--positive-count", type=int, default=300)
    ap.add_argument("--negative-count", type=int, default=300)
    ap.add_argument("--heldout-positive-count", type=int, default=20)
    ap.add_argument("--heldout-negative-count", type=int, default=20)
    ap.add_argument("--target-seconds", type=float, default=2.0)
    args = ap.parse_args(argv)

    if not have_ffmpeg():
        sys.stderr.write("ffmpeg not on PATH; install it (this script needs resampling).\n")
        return 2
    if not OMNIVOICE_BIN.is_file():
        sys.stderr.write(f"OmniVoice binary missing at {OMNIVOICE_BIN}\n")
        return 2
    if not TTS_MODEL.is_file() or not TTS_CODEC.is_file():
        sys.stderr.write("OmniVoice gguf/codec missing — check eliza-1 bundle install.\n")
        return 2

    out_dir = args.out_dir.resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    tmp_dir = out_dir / "_tmp"
    tmp_dir.mkdir(parents=True, exist_ok=True)

    positives_dir = out_dir / "positives"
    negatives_dir = out_dir / "negatives"
    heldout_pos_dir = out_dir / "heldout-positives"
    heldout_neg_dir = out_dir / "heldout-negatives"

    started = datetime.now(timezone.utc).isoformat()

    n_pos = synthesize_set(
        positives_dir,
        phrases=["hey eliza"],
        instructs=INSTRUCTS,
        count=args.positive_count,
        seed_base=1000,
        label="pos",
        tmp_dir=tmp_dir,
    )
    n_neg = synthesize_set(
        negatives_dir,
        phrases=DISTRACTOR_PHRASES,
        instructs=INSTRUCTS,
        count=args.negative_count,
        seed_base=20000,
        label="neg",
        tmp_dir=tmp_dir,
    )
    n_hpos = synthesize_set(
        heldout_pos_dir,
        phrases=["hey eliza"],
        instructs=INSTRUCTS,
        count=args.heldout_positive_count,
        seed_base=50000,
        label="hpos",
        tmp_dir=tmp_dir,
    )
    n_hneg = synthesize_set(
        heldout_neg_dir,
        phrases=DISTRACTOR_PHRASES,
        instructs=INSTRUCTS,
        count=args.heldout_negative_count,
        seed_base=70000,
        label="hneg",
        tmp_dir=tmp_dir,
    )

    finished = datetime.now(timezone.utc).isoformat()

    shutil.rmtree(tmp_dir, ignore_errors=True)

    manifest = {
        "phrase": "hey eliza",
        "started": started,
        "finished": finished,
        "ttsBackend": {
            "tool": "llama-omnivoice-server (eliza-fused fork)",
            "binary": str(OMNIVOICE_BIN),
            "model": str(TTS_MODEL),
            "codec": str(TTS_CODEC),
            "sourceRepo": "elizaOS/llama.cpp (eliza-fused fork)",
            "modelSource": "Serveurperso/OmniVoice-GGUF (Apache-2.0)",
            "outputSampleRateHz": 24000,
            "resampledToHz": TARGET_SAMPLE_RATE,
        },
        "counts": {
            "positives": n_pos,
            "negatives": n_neg,
            "heldoutPositives": n_hpos,
            "heldoutNegatives": n_hneg,
        },
        "voiceInstructs": INSTRUCTS,
        "distractorPhrases": DISTRACTOR_PHRASES,
        "targetSeconds": args.target_seconds,
        "license": {
            "OmniVoice": "Apache-2.0",
            "syntheticAudio": "derived from OmniVoice (Apache-2.0); head is redistributable",
        },
    }
    (out_dir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"[synth] wrote manifest -> {out_dir / 'manifest.json'}")
    print(f"[synth] DONE pos={n_pos} neg={n_neg} hpos={n_hpos} hneg={n_hneg}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
